### ISSUE TITLE
Don't fail Federalist dev instance-launched builds when log/status requests fail

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build#105]
Updated based on discussion below:

For dev instances, set an env var (like `SKIP_LOGGING`) from the web app. This var should indicate to the build container to skip POSTing logs and build statuses back to the originating web app (which is a local instance that can't be reached).

~We should capture exceptions and continue when requests to logging endpoints fail. This will allow builds from dev instances to succeed even though the logs cannot be posted back to our local instances.~

~The previous build container code did not fail when log requests failed, so this is a regression.~

**Comment by wslack** [comment]
This is a dev only issue?

**Comment by wslack** [comment]
(also, how important of a regression is it?)

**Comment by jseppi** [comment]
Mostly a dev issue. Depends on if we want real builds to fail if logs can’t be posted for some reason. 

It’s a pretty small lift to implement the fix.

**Comment by wslack** [comment]
"real builds" = you mean builds in prod? If builds in prod are at risk, we should def fix. If builds are only at risk for dev instances, it depends on how much you hit the problem in your dev work, so I leave it to your judgment compared to the other issues currently getting work.

cc @leahbannon as an example of how we prioritize

**Comment by jseppi** [comment]
Currently, if for some reason the web app or the builder app were to go down, then builds would also fail because the process would break on the logs/statuses not POSTing. But since builds are not removed from the SQS until they succeed, they would be tried again until able to post back to the web app/builder. I wouldn't necessarily call it a risk since that system is resilient.

**Comment by wslack** [comment]
Isn't that a good thing? I would want builds to only complete if they can post logs.

**Comment by jseppi** [comment]
It's not necessarily a bad thing :)

For developing we do probably want to be able to launch builds that succeed from our local instances. We could do something like passing another env var (like `SKIP_LOGGING`) when we do builds from our dev instances.

**Comment by wslack** [comment]
Ah - and no builds can succeed locally right now?

I guess I would prefer the variable to allowing builds to complete without logging. (since a "incomplete" build is still going to deploy to S3)

**Comment by jseppi** [comment]
Correct, no builds launched from local instances can complete. They actually don't even get through the clone step (so no files are published to S3 either) since the first logs are sent right after the cloning finishes (and thus the build breaks there).

I'm 👍 to setting and env var flag (or some other similar implementation once I take a closer look) to indicate not to fail on logs/statuses.

**Comment by wslack** [comment]
👍 understood. Makes sense to put this in "ready" then.
