### ISSUE TITLE
Reduce build container image size

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build#112]
It's currently `1.07GB`, which with the current cloud.gov app cap of `2GB` leaves less than `1G` of space for site builds themselves.

We'll soon (maybe by tomorrow) be able to allocate more than `2GB` to the cloud.gov app instances, but it would still be a good practice to reduce the image size.

**Comment by jseppi** [comment]
Doesn't seem very important any more, but would be a best practice kind of thing. Iceboxing.

**Comment by wslack** [comment]
Hmmm. I don't know; if there are low-lift fixes it might not be a bad idea to ensure the container is efficient?

If nothing obvious I think we can close.

**Comment by wslack** [comment]
👍 moving back to icebox

**Comment by davemcorwin** [comment]
We have an updated issue tracking this.
