### ISSUE TITLE
Log `stderr` in addition to `stdout`

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build#113]
We believe some error messages that would be helpful to both us and partners for debugging unsuccessful builds are not properly recorded in build logs. This is likely due to only logging `stdout` and not `stderr` (ref https://github.com/18F/federalist-garden-build/blob/staging/tasks/main.py#L91)

**Comment by wslack** [comment]
Expected Effort? If low, I think this should probably jump to Ready.

**Comment by jseppi** [comment]
Yes, low effort.

**Comment by jseppi** [comment]
Interestingly, in the case of exceptions, we were _only_ logging `stderr`, but sometimes it looks like `stdout` also contains helpful information (such as the the case when `bundle install` fails).
