### ISSUE TITLE
Implement New Relic "background task" monitoring

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build#116]
#### Description of feature or bug

More info/context in https://github.com/18F/federalist-garden-build/issues/79#issuecomment-362703536

#### Definition of done

Build container code is instrumented and reporting in our New Relic dashboard.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

1. Add New Relic background task decorator or context manager to overarching tasks (main, clone, build, publish).
1. Add/read necessary config values from the cf env or vcap services.
1. Ensure reporting works properly in staging.

**Comment by wslack** [comment]
Priority, what do you think?

**Comment by jseppi** [comment]
I'd put this as a nice-to-have, but not totally necessary right now. It might become more necessary as Federalist grows though.

**Comment by wslack** [comment]
kk dropping in backlog

**Comment by wslack** [comment]
@amirbey to merge into his existing issue

**Comment by wslack** [comment]
@amirbey is going to fold the end goal of this into his healthcheck issue https://github.com/18F/federalist/issues/1833. Otherwise we can close this.
