### ISSUE TITLE
Test coverage badge and report are not working

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build#129]
#### User Story
As a Federalist developer, I want to see how my code changes affect my test coverage %.

#### Background from James
README badge is not reporting any coverage:

<img width="641" alt="screen shot 2018-06-20 at 10 42 55 am" src="https://user-images.githubusercontent.com/697848/41669153-bfee7ea8-7476-11e8-837f-3ad7f7a7f2d1.png">

[Code Climate dashboard](https://codeclimate.com/github/18F/federalist-garden-build) also shows no coverage reporting:

<img width="424" alt="screen shot 2018-06-20 at 10 43 45 am" src="https://user-images.githubusercontent.com/697848/41669184-d49fc5e6-7476-11e8-8b26-d4ec9ff10dc0.png">

Maybe the reporting was tied to my Code Climate account key or something and it broken after I left the 18F org?

#### Acceptance Criteria
- [x] The Code Climate test coverage icon displays a numeric percentage value

#### Level of Effort
Low

**Comment by wslack** [comment]
huh odd. https://codeclimate.com/github/18F/federalist-garden-build still works

**Comment by wslack** [comment]
But I get a PERMISSION DENIED screen when I got to set up test coverage

**Comment by wslack** [comment]
I wonder if someone with admin on the repo has to authorize code climate.

**Comment by amirbey** [comment]
#### User Story
A user can visit the repo and see a numeric percentage value for test coverage

#### Acceptance Criteria
- [ ] The Code Climate test coverage icon displays a numeric percentage value

#### Level of Effort
Low

**Comment by wslack** [comment]
I edited ^^ into James's initial comment.
