### ISSUE TITLE
Create a default 404 page for builds with a private bucket

### ISSUE THREAD

**Issue by apburnes** [18F/federalist-garden-build#169]
#### User Story

When a user builds a site hosted in a private S3 bucket, create a default 404 page for the site.

#### Background (Optional)

Currently, the shared bucket uses a default 404 page created for all sites. This will generate the default 404 page every time a site is built in a private S3 bucket. Adding this action may allow for site to be able to generate custom 404 pages.

#### Acceptance Criteria

- [ ] federalist-garden-build generates a default `404.html` for private bucket builds.
- [ ] If `site/owner/repo/404.html` exists in static site build,  we don't generate a default '404.html'
- [ ] Change made live via deploy of garden-build.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] After building a site's static files, check to see if a `404.html` exists
- [ ] If non `404.html` exists, generate `404.html` from [federalist-404-page](https://github.com/18F/federalist-404-page)
- [ ] Allow site publishing to go forward as usual.
- [ ] Update [federalist website config](https://github.com/18F/federalist/blob/staging/api/services/S3Helper.js#L27-L39) to point to `/site/<OWNER>/<REPO>/404.html`

**Comment by amirbey** [comment]
hi @apburnes - here  is the PR where we removed the 404 in the build process
https://github.com/18F/federalist-garden-build/commit/8ee5acfee3db2df1965e55df96a87e11824d1781

**Comment by apburnes** [comment]
Thanks!
