### ISSUE TITLE
Research how to manage environment for build scripts

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist-garden-build#22]
When we run our scripts we should make sure that their environment inherits the minimum environment variables necessary for them to do their work.

When this gets resolved, we should open an issue for the execution.

**Comment by jmhooper** [comment]
The build environment is currently controlled by using `unset` to remove environment variables before running any user provided code.

ref: https://github.com/18F/federalist-docker-build/blob/master/build.sh#L11

This is problematic b/c it requires developers to opt-out of environment variables when adding secrets to the container. This too easily leads to a situation where someone adds a secret to the container environment and neglects to unset it in the build script. This would result in that secret being leaked into parts of the system where unprivileged users can reach it.

To reduce the risk of leaking secrets in the container environment, we should adjust to system so that developers must opt-in to what is available in the container's build scripts. With such a system in place we would have to explicitly list the environment variables we wish to make accessible to users building sites in the containers.

There are a number of solutions that we've considered:

- Using the [`env` command](https://linux.die.net/man/1/env) with the `-i` option to run the scripts in a clean environment plus the environment variables the users need to build their sites
- Creating a separate user that builds the sites in a chroot jail

There are a number of pitfalls to both, some of which we may not fully understand at this point. We should plan to run this problem by a few people with more sysadmin experience before moving too much further with this.

**Comment by jmhooper** [comment]
I spoke with @LinuxBozo about this issue and he recommended a couple paths.

The desirable solution involves using 2 containers, a parent container which clones and publishes the site, and then a child container which actually builds the site. The child container would be run inside the parent container with it's own environment that did not contain the secrets. This is where the user provided code would execute. In order for this to work, we'd need to verify that we can start a privileged container with Diego, otherwise our container will not be able to start any child containers.

If that is not an option, the other path would involve cleaning the secrets out of the environment, writing them to an env file, then building the site in a chroot jail as mentioned above. When the build was finished, we could then reload the secrets from the environment file and publish the site.

**Comment by wslack** [comment]
@jmhooper is this under active work or should we move back to ready?

**Comment by jmhooper** [comment]
Hmm. Let's move it back to ready for now. This is a pretty significant body of work.

**Comment by jmhooper** [comment]
@yozlet has suggested this could be handled by moving the build onto a CI like [concourse](https://concourse.ci/). That way the necessary env vars could be handed down to only the parts of the build that need them.

In addition, it looks like cloud.gov is on its way to offering CI as a Service with Concourse.

**Comment by jmhooper** [comment]
Another option that is a bit more complex:

We could have 2 containers, a build container and a clone/publish container.

The clone/publish container would be launched by the builder. It would clone the site, zip it, and then start a server listening for a request to download the site and a request to upload the site. Then it would start the build container.

The build container would receive 2 secrets, a token for downloading the site and a token for uploading the site. To start it would send a request to the clone/publish container to download the zipped site. Then it would build the site. At that point, it would begin building the site. When finished, it would zip and upload the results to clone/publish container.

After the clone/publish container received the uploaded site, it would unzip and upload it to S3.

**Comment by jseppi** [comment]
Closed because the new build container https://github.com/18f/federalist-garden-build-py uses PyInvoke's `env` argument to sub-commands to specify only the necessary environment variables to each command. That way, sensitive environment variables are not exposed to steps that run user-controlled code (like `jekyll build` or `npm run federalist`).
