### ISSUE TITLE
Deprecate “redirect object” creation

### ISSUE THREAD

**Issue by amirbey** [18F/federalist-garden-build#229]
#### User Story

A Federalist user should implement valid links throughout their site and not rely on the build process to create redirect objects for invalid links  to valid links.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] site links generate 404 if invalid
- [ ] Change made live via deploy of garden build

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] inform site operators of the upcoming change via email or site notification
- [ ] remove redirect object creation from the publish phase
- [ ] add a link checker? displayed in logging and report status to GitHub

**Comment by davemcorwin** [comment]
Captured in the Epic: https://github.com/18F/federalist-garden-build/issues/248
