### ISSUE TITLE
Count number of files produced

### ISSUE THREAD

**Issue by wslack** [18F/federalist-garden-build#26]
When the container is complete, it can log the number of files produced for the S3 bucket for future audits.

**Comment by jseppi** [comment]
We do log the files that are new/modified/deleted from the contents in the S3 bucket: 

```
[S3_PUBLISHER] 2017-11-29 18:57:29 INFO: New: 1
[S3_PUBLISHER] 2017-11-29 18:57:29 INFO: Modified: 1
[S3_PUBLISHER] 2017-11-29 18:57:29 INFO: Deleted: 0
```

Does this need additional information? Maybe something like "Total site files produced: 405"?

**Comment by wslack** [comment]
Depends on the use case. I think this allows us to compare the actual contents of the S3 bucket with the build report. (since presumably, someone attacking the S3 bucket wouldn't be able to modify the logs)

The question is how likely that attack vector is....

**Comment by jseppi** [comment]
Right on. It would be easy to output the total number of files of produced after a build (ie, just count the files in the `_site` directory).
