### ISSUE TITLE
Add authentication to / migrate from docker registries

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist-garden-build#272]

**Comment by davemcorwin** [comment]
Looking at the process here (https://docs.docker.com/registry/deploying/#native-basic-auth) We can't run the docker image in that way on cloud.gov since we can't bind volumes and we don't have access to a file system.

Options:
1. Use an nginx proxy (using the nginx buildpack) to provide basic auth and make sure the registry is only available on an internal route by follow the steps here (https://docs.docker.com/registry/recipes/nginx/).
2. Migrate to AWS ECR in GovCloud. 

My thoughts:
If we were starting from scratch, I would rather use AWS ECR so we don't have to manage our own registries. It's available in GovCloud and can be configured via Terraform. The first solution above will still require creating a new repo with 2 applications (nginx, docker registry) and updating our deployment infrastructure to configure and deploy the applications correctly and add authentication when accessing the registry.

@amirbey @apburnes thoughts?

**Comment by apburnes** [comment]
AWS ECR seems to be the low maintenance, long term solution. Outside some initial investment in compliance and logistics, it should be plug and play.  The only advantage of nginx is possibly no additional compliance work. With Docker Hub introducing [new rate limits](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/), Federalist's use of AWS ECR could also inform Cloud.gov's decisions if they run into issues with rate limiting.

Go with AWS ECR option.

**Comment by davemcorwin** [comment]
I have a good sense of how to integrate AWS ECR, but have one other idea that might be fine for now and is less work. Our current CI/CD process just builds a new container, pushes it to a registry (overwriting the previous one), and immediately deploys it to cloud.gov. We aren't actually using the registry for anything, such as versioning or storage so the image can be pulled from separated processes. I am confirming with cloud.gov, but the easiest thing to do is just not use a permanent registry at all. We can just deploy from the local registry we spin up in CI/CD. We can still back it with S3 so we have them stored, or just use the local file system, I'm not sure about the value of backing with S3 considering that we don't version them.

@amirbey @apburnes thoughts?

**Comment by davemcorwin** [comment]
It looks like CF won't push from a local registry that doesn't have SSL, so probably back to ECR, darn.
