### ISSUE TITLE
Implement log drain for garden build instead of writing logs to db. Ex. fluentd, logstash, etc

### ISSUE THREAD

**Issue by amirbey** [18F/federalist-garden-build#331]
#### Background (Optional)

https://www.fluentd.org/
https://www.elastic.co/logstash/

https://gsa-tts.slack.com/archives/G7EFTFW03/p1628479882002600

#### Acceptance Criteria

- [ ] logs are processed via log drain as opposed to directly writing to the database
- [ ] Change made live via federalist-garden-build

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by davemcorwin** [comment]
Captured in [Epic](https://github.com/18F/federalist-garden-build/issues/248).
