### ISSUE TITLE
Exclude Dockerfile and docker-compose.yml from builds?

### ISSUE THREAD

**Issue by amirbey** [18F/federalist-garden-build#343]
#### User Story

A site visitor user should not be able to render the docker-compose.yml file at the site root.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] proxy redirects docker-compose.yml requests to 404.html
- [ ] Change made live via federalist-proxy

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by svenaas** [comment]
(If you just got notified of this as a new issue it's because I just transferred it from `federalist-proxy` to `federalist-garden-build` where we intend to address it.)

**Comment by svenaas** [comment]
Provisional implementation on PR #353 based on @davemcorwin's suggestion of configuring this in `federalist.json`; I defer to y'all on whether you want to adopt it or go a different way. I think the stickiest bit is probably that in going with the existing directory/file matching schedule in `federalist.json` I didn't see an obvious way to exclude/include a pattern in _arbitrary_ places within the site — for instance, to exclude files named `Dockerfile` regardless of the folder they're in. 

Perhaps this is sufficient for Federalist sites. If not, the existing matching behavior could be extended for exclusion/inclusion as well as headers. Or the exclusion/inclusion could be handled separately using a `.federalistignore` / `.pagesignore` file or something with more of a `.gitignore` schema. 

Those are my thoughts, and that's where I'm leaving this one for now. I'm going to unassign myself but leave this in In Progress.
