### ISSUE TITLE
Use a higher level language instead of bash?

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build#52]
The bash scripts in this repo are, I think, complex enough to warrant using a higher-level language instead. Doing so will likely make testing (which is currently not done at all) easier, which should be a pretty high priority in my opinion.

To Do:
- [x] Determine what to do with repos. That is, should we continue using https://github.com/18F/federalist-garden-build, or archive it and switch to https://github.com/18F/federalist-garden-build-py?
  - federalist-garden-build-py has a full git history of federalist-garden-build.
- [x] Update relevant sections of federalist-docs
- [x] https://github.com/18F/federalist-garden-build#development--making-changes

**Comment by jseppi** [comment]
Re: testing, I think mocking external services would be easier/possible with a higher-level lang.

**Comment by jseppi** [comment]
Because publish.rb is already in ruby, that is one option for a language, though I am personally not a ruby dev.

Python might be a pretty good option.

**Comment by wslack** [comment]
@jseppi is there an active benefit to changing them besides making tests easier?

I say that because the contents of this repo are scanned before new deployments, so automated testing is of less benefit than with other repos.

**Comment by jseppi** [comment]
I think security scanning is fairly different from testing the code for functionality.

Basically right now we have no idea if changes to any of the code here will work/break existing functionality/etc. Proper testing would help with that, as well as with understanding the code here.

**Comment by jseppi** [comment]
And it seems like the functionality here is only going to get more complicated with things like adding hugo support and solving for #22.

**Comment by wslack** [comment]
🤔 hmmm let's discuss in Monday standup. What do you think the LOE is to accomplish this task? Hours? Days? Weeks?

**Comment by jseppi** [comment]
Somewhere within Days - Week most likely. Definitely worth discussing.

**Comment by jmhooper** [comment]
👍  to this

**Comment by jseppi** [comment]
Maybe even `go` for type safety??

**Comment by wslack** [comment]
Let's discuss in standup today and prioritize this relative to Hugo.

**Comment by wslack** [comment]
Large effort, but pays down long term technical debt. Secondary project.

**Comment by wslack** [comment]
Would likely be python.

**Comment by wslack** [comment]
Hold on closing until merge and resolved.

**Comment by wslack** [comment]
We moved everything to https://github.com/18F/federalist-garden-build and archived https://github.com/18F/federalist-garden-build-py.

**Comment by wslack** [comment]
Updated federalist-docs
