### ISSUE TITLE
Update README and repo description to reflect that hugo can also be used

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build#56]
The README and repo description only mention that Jekyll is used to build sites, but since #51 was merged, hugo is also a valid build engine.

We should update all docs to say something like "a static site build engine" in place of "Jekyll" and include a list of supported build engines (only jekyll and hugo for now).

**Comment by wslack** [comment]
Should we hold on this until Hugo stops being experimental?

**Comment by jseppi** [comment]
Got my browser tabs crossed up, sorry for the noise!
