### ISSUE TITLE
Local script to do deployments of the container

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build#58]
It would be good if there was a script to do deployments of this image to `staging` and `prod` without having to manually follow all the steps in https://federalist-docs.18f.gov/pages/how-federalist-works/cloud-gov-setup/#pushing-a-federalist-docker-build-image-to-the-registry

I'm thinking of something that would locally spin up a registry backed by the S3, take an env (ie `staging` or `prod`), and run all the steps to build, push, and verify the image. I guess the Clair stuff should also be included in such a script, but I don't yet have a good handle on how that works.

I _think_ we could make a nice docker-compose setup to do this.

**Comment by davemcorwin** [comment]
Closing.

We have a miniature version of this that is included in #214 and will be superseded by moving the deployment to Circle along with the build in #221.
