### ISSUE TITLE
BASEURL default value is not working for hugo builds

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build#72]
When there is a custom (demo) domain, `federalist-builder` sets an empty value for `BASEURL` that is set in the env for the target `federalist-garden-build-container`.

When `BASEURL` is empty, we should call hugo with `hugo --baseURL '' ...`. However, the "default" value expression `${BASEURL-"''"}` appears to not be correct because it instead evaluates to a completely empty string without the single quotation marks, which results in the string `--source` being set as the base url instead of being evaluated as a command flag.

```sh
hugo --baseURL ${BASEURL-"''"} --source . --destination ./_site
````

**Comment by jseppi** [comment]
I was able to get a local repro of the bug with this very minimal script:

```sh
#!/bin/bash

BASEURL=
hugo --baseURL ${BASEURL-"''"} --source . --destination ./_site
```

If I totally remove the `BASEURL=` line, then the call to hugo works as expected. The problem is the default value substitution as currently written only works when `BASEURL` is completely undefined instead of already defined as an empty string.

The fix is to instead do default value substitution like this: `${BASEURL:-"''"}` (note the `:`)

**Comment by wslack** [comment]
oh wow. Ok! I assume you have the PR, or should I file it?

**Comment by jseppi** [comment]
Heh, not so fast, passing in `''` to `--baseURL` also doesn't work as expected because hugo interprets the `''` literally instead of as empty string, so we need to still be a little smarter.

I'll have a PR shortly.

**Comment by wslack** [comment]
Good job team!
