### ISSUE TITLE
publish.rb attempts to delete wrong files

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build#77]
Just happened to notice while porting this to python. If two repos under the same owner share basically the same name, then the logic to determine files to delete improperly identifies files under the second site. Luckily, the deletion logic won't actually work to delete those files, but the logs are confusing.

Example:
site 1: `jseppi/test-federalist-site`
site 2: `jseppi/test-federalist-site-2`

When publishing `jseppi/test-federalist-site`, the `prefix` argument sent to S3's `list_files` API will also get the objects with keys that are prefixed with `jseppi/test-federalist-site-2` since the former is a substring of the latter.

Logs will look like this (notice the `-2` in the files being deleted):

```
...
Deleting: site/jseppi/test-federalist-site/-2/assets/vendor/uswds/fonts/merriweather-bold-webfont.eot... Done (0.015464146s)
Deleting: site/jseppi/test-federalist-site/-2/assets/vendor/uswds/fonts/merriweather-bold-webfont.ttf... Done (0.014940206s)
Deleting: site/jseppi/test-federalist-site/-2/assets/vendor/uswds/fonts/merriweather-bold-webfont.woff... Done (0.017011489s)
...
```

The path to actually delete files is reconstructed in a manner that won't actually delete the second site's files, but it does lead to confusing logs.

cc @jmhooper

**Comment by jmhooper** [comment]
Oh wow, good catch

**Comment by jseppi** [comment]
I should have it fixed in the new stuff, and given that it doesn't _actually_ delete anything incorrectly, I think it can wait for the new builder.

**Comment by jseppi** [comment]
`publish.rb` isn't used any more and this problem was fixed with the new python code
