### ISSUE TITLE
Explore/add New Relic process monitoring

### ISSUE THREAD

**Issue by wslack** [18F/federalist-garden-build#79]
Not totally sure if this is possible, but adding New Relic to monitor processes and collect errors might be a good idea. 

The reasons I'm not totally sure about it working are 
1) this is not a web app, 
2) the containers are "ephemeral", 
3) the containers sleep after each use, which might end up being kinda funky in NR, and 
4) since sub-commands are basically shell'd out, I'm not sure if NR could "globally" track anything in them.
  
Done: when we do this or decide its not a good idea

**Comment by jseppi** [comment]
New Relic is primarily for web apps, but there are ways to instrument "background tasks" - https://docs.newrelic.com/docs/agents/python-agent/supported-features/python-background-tasks

**Comment by jseppi** [comment]
Also, this is somewhat related to https://github.com/18F/federalist-builder/issues/60 in that it serves a similar purpose -- knowing if containers are up or not.

My hope is that adding NR will add more than just "uptime" monitoring and will alert us for other types of failures.

**Comment by jseppi** [comment]
Ok, this definitely is doable, and exceptions look like they can be tracked, which is nice.
It'll take a little work (on the low end) to add all the instrumentation and make it nice, but I'm 👍 on doing this.

I hooked up the NR agent while running the build container locally.

Here's what an exception looks like (but only have them getting tracked in the `main` task currently):

<img width="1131" alt="screen shot 2018-02-02 at 1 41 06 pm" src="https://user-images.githubusercontent.com/697848/35754215-4009db8e-0828-11e8-8f7e-3e9be08ea28f.png">

What I haven't figured out how to get logged are exceptions that happen in sub-tasks. Might need to add the NR decorator or context manager to each task.

If I'm interpreting these graphs correctly, we'll also be able to track build time metrics:

<img width="645" alt="screen shot 2018-02-02 at 1 45 00 pm" src="https://user-images.githubusercontent.com/697848/35751799-5b0a0d2c-081f-11e8-8f76-0ab17425c4bb.png">

We can also setup conditions to start alerting us when build errors reach a certain threshold.

**Comment by jseppi** [comment]
Closing this exploration task and opening https://github.com/18F/federalist-garden-build/issues/116 to track the actual implementation.

**Comment by wslack** [comment]
reopened so that we can recap at Retro!
