### ISSUE TITLE
Achieve full test coverage in build container

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist-garden-build#82]
- [ ] test everything
- [x] add coverage reporting integration with CodeClimate.

**Comment by wslack** [comment]
This is for the builder only, correct?

**Comment by jseppi** [comment]
For the build container, yes.

**Comment by jseppi** [comment]
After #126 is merged, then I think this can be closed.

I opened #127 for the last chunk of code that needs to have tests covering it.
