### ISSUE TITLE
For jekyll builds, create _config.yml if it doesn't exist

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build#92]
The new build container only appends custom configs to `_config.yml` if it exists. The old one would create `_config.yml`  if it didn't exist. Some sites, like https://github.com/18F/fedramp-dashboard/blob/federalist/gulpfile.js, relied on the previous behavior.

We need to modify the new builder to behave the same way.

**Comment by wslack** [comment]
Should we do this? I get that the regression is an issue, but which is the better long term behavior? I don't like putting files in the build process that aren't in the repo.

**Comment by jseppi** [comment]
Yes. If we don't, then actually none of the jekyll custom config is passed on (because they get appended to the `_config.yml`).

**Comment by wslack** [comment]
kk. Just seems odd for someone to apply custom config to a site without a config file.

**Comment by jseppi** [comment]
Yeah, kinda. But there's nothing in the UI that would explain or prevent it either. And Jekyll apparently doesn't need a config file at all.

**Comment by wslack** [comment]
ah, fair then.
