### ISSUE TITLE
UnicodeEncodeError: surrogates not allowed / Dealing with invalid characters in filenames

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build#98]
We recently had an issue where a user's site repository contained filenames that had smart quotes and smart apostrophes. For example: `accomplishing-agency’s_view=public.html`

The upload will choke on these, somewhere down in boto when it attempts to do do an `encode`:

```
...
  File "/usr/local/lib/python3.6/site-packages/botocore/utils.py", line 332, in percent_encode
    input_str = input_str.encode('utf-8')
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 131-133: surrogates not allowed
```

I don't quite know what that `UnicodeEncodeError` means other than it doesn't seem to like the `’` character.

This article might shed some light on the situation: http://lucumr.pocoo.org/2013/7/2/the-updated-guide-to-unicode/

**Comment by jseppi** [comment]
@commit-dkp: are you familiar with these kinds of encoding problems?

**Comment by commit-dkp** [comment]
@jseppi https://unicodebook.readthedocs.io/issues.html#strict-utf8-decoder might shed some light on this for you.  The article you linked has it right, "strings received from functions that might carry surrogates need to be resolved before passed to APIs not dealing with such strings."

**Comment by wslack** [comment]
Working to complete in https://github.com/18F/federalist-garden-build/pull/100

**Comment by amirbey** [comment]
chatte with @commit-dkp  and he said James' solution is a good security measure (and temp fix) preventing the upload of files with surrogate unicode characters, however, the explanation provided does not make it clear why the upload is failed.  It would be helpful to be more specific and identify/present the offending surrogates so the user can make the appropriate corrections. 

Note: Indentifying the surrogate characters means that the system can then also removed the surrogate characters on the users behalf; however, it then presents the issue of users not being angle to find their files b/c they expect them in the location named with surrogates. So most likely not hte best option.

**Comment by wslack** [comment]
@amirbey do you think this should be medium instead of low? I think we're only supposed to groom for priority as a group.
